only_rules: # only these rules will be applied
    - anyobject_protocol
    - array_init
    - attributes
    - class_delegate_protocol
    - closing_brace
    - closure_end_indentation
    - closure_parameter_position
    - closure_spacing
    - colon
    - comma
    - compiler_protocol_init
    - conditional_returns_on_newline
    - contains_over_first_not_nil
    - control_statement
    - discouraged_direct_init
    - discouraged_object_literal
    - discouraged_optional_boolean
    - dynamic_inline
    - empty_enum_arguments
    - empty_parameters
    - empty_parentheses_with_trailing_closure
    - explicit_init
    - file_length
    - force_try
    - force_unwrapping
    - function_body_length
    - generic_type_name
    - identical_operands
    - identifier_name
    - implicit_getter
    - is_disjoint
    - large_tuple
    - leading_whitespace
    - legacy_cggeometry_functions
    - legacy_constant
    - legacy_constructor
    - legacy_hashing
    - legacy_nsgeometry_functions
    - legacy_random
    - line_length
    - literal_expression_end_indentation
    - mark
    - modifier_order
    - multiline_arguments
    - multiline_function_chains
    - multiple_closures_with_trailing_closure
    - operator_usage_whitespace
    - operator_whitespace
    - overridden_super_call
    - override_in_extension
    - prohibited_super_call
    - protocol_property_accessors_order
    - redundant_discardable_let
    - redundant_nil_coalescing
    - redundant_objc_attribute
    - redundant_optional_initialization
    - redundant_void_return
    - return_arrow_whitespace
    - shorthand_operator
    - statement_position
    - switch_case_alignment
    - syntactic_sugar
    - trailing_comma
    - trailing_semicolon
    - type_name
    - type_body_length
    - unneeded_break_in_switch
    - unused_enumerated
    - unused_optional_binding
    - valid_ibinspectable
    - vertical_parameter_alignment
    - vertical_parameter_alignment_on_call
    - vertical_whitespace
    - void_return
    - weak_delegate
    - yoda_condition

# The values below are not final and may need further tweaking.

file_length:
  - 2000 #warning
  - 2500 #error

function_body_length:
  - 200 #warning
  - 400 #error

line_length:
  - 200 #warning
  - 400 #error

type_body_length:
  - 1000 #warning
  - 2000 #error

identifier_name:
  min_length: 1 #warning
  max_length: #warning or error
    warning: 100
    error: 150

type_name:
    min_length: 1
    max_length: 80 #warning

excluded:
  - Playgrounds.*
  - Pods
  - R.generated.swift
  - .build # Where Swift Package Manager checks out dependency sources
  - build

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)